// Demo data for MarketPulse AI UI
// This data simulates what the real API would return

import { SectorData, StockData, NewsArticle, GeopoliticalEvent, MarketOverview } from './types';

export const DEMO_SECTORS: SectorData[] = [
  {
    id: 'energy',
    name: 'Energy & Oil',
    icon: '⛽',
    sentiment: 74,
    trend: 'up',
    trendStrength: 2,
    keyDriver: 'Crude rallying on OPEC+ cuts; Reliance refinery margins strong',
    change24h: +5.2,
    stocks: ['RELIANCE', 'ONGC', 'IOC', 'BPCL', 'GAIL'],
    globalExposure: 'Middle East tensions keeping oil above $82',
  },
  {
    id: 'power',
    name: 'Power & Utilities',
    icon: '⚡',
    sentiment: 82,
    trend: 'up',
    trendStrength: 3,
    keyDriver: 'Govt pushes 500GW renewable target; Adani Green orders surge',
    change24h: +8.1,
    stocks: ['NTPC', 'POWERGRID', 'TATAPOWER', 'ADANIGREEN', 'JSWENERGY'],
    globalExposure: 'Global green transition policies accelerating investments',
  },
  {
    id: 'auto',
    name: 'Automobile',
    icon: '🚗',
    sentiment: 65,
    trend: 'up',
    trendStrength: 1,
    keyDriver: 'Strong domestic sales data; monsoon outlook positive for rural demand',
    change24h: +2.3,
    stocks: ['MARUTI', 'TATAMOTORS', 'M&M', 'BAJAJ-AUTO', 'HEROMOTOCO'],
    globalExposure: 'Semiconductor supply normalizing; steel prices softening',
  },
  {
    id: 'gold',
    name: 'Gold & Precious Metals',
    icon: '🥇',
    sentiment: 78,
    trend: 'up',
    trendStrength: 2,
    keyDriver: 'Global uncertainty driving safe-haven demand; central bank buying',
    change24h: +4.7,
    stocks: ['TITAN', 'MUTHOOTFIN', 'MANAPPURAM', 'KALYANFIN', 'SENCO'],
    globalExposure: 'Weak USD & geopolitical risks pushing gold above $2,400',
  },
  {
    id: 'ev',
    name: 'Electric Vehicles',
    icon: '🔋',
    sentiment: 71,
    trend: 'up',
    trendStrength: 2,
    keyDriver: 'FAME III policy boost; Tata & Mahindra EV sales up 40% YoY',
    change24h: +3.8,
    stocks: ['TATAMOTORS', 'M&M', 'OLECTRA', 'EXIDEIND', 'KPITTECH'],
    globalExposure: 'Lithium prices stabilizing; China EV exports concern EU markets',
  },
  {
    id: 'banking',
    name: 'Banking & Finance',
    icon: '🏦',
    sentiment: 58,
    trend: 'flat',
    trendStrength: 1,
    keyDriver: 'RBI holds rates; NPA concerns in mid-cap banks offset credit growth',
    change24h: -1.2,
    stocks: ['HDFCBANK', 'ICICIBANK', 'SBIN', 'KOTAKBANK', 'AXISBANK'],
    globalExposure: 'Fed rate cut expectations boosting FII inflows',
  },
  {
    id: 'it',
    name: 'IT & Technology',
    icon: '💻',
    sentiment: 52,
    trend: 'flat',
    trendStrength: 1,
    keyDriver: 'Weak US hiring data offsets favorable rupee; AI adoption mixed',
    change24h: -0.8,
    stocks: ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM'],
    globalExposure: 'US recession fears; clients delaying discretionary spending',
  },
  {
    id: 'pharma',
    name: 'Pharma & Healthcare',
    icon: '💊',
    sentiment: 45,
    trend: 'down',
    trendStrength: 1,
    keyDriver: 'FDA observations at two major facilities; generic pricing pressure',
    change24h: -3.5,
    stocks: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'APOLLOHOSP', 'BIOCON'],
    globalExposure: 'US Biosecure Act may benefit Indian CDMO companies',
  },
  {
    id: 'defense',
    name: 'Defense & Aerospace',
    icon: '🛡️',
    sentiment: 85,
    trend: 'up',
    trendStrength: 3,
    keyDriver: 'Record defense budget; HAL delivers ahead of schedule; export orders',
    change24h: +6.9,
    stocks: ['HAL', 'BEL', 'BHEL', 'MAZAGON', 'COCHINSHIP'],
    globalExposure: 'Global defense spending surge; India-Russia defense deals',
  },
  {
    id: 'metals',
    name: 'Metals & Mining',
    icon: '⛏️',
    sentiment: 42,
    trend: 'down',
    trendStrength: 2,
    keyDriver: 'China demand slowdown; global steel oversupply concerns',
    change24h: -4.1,
    stocks: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL', 'COALINDIA'],
    globalExposure: 'China property crisis dragging commodity demand',
  },
  {
    id: 'fmcg',
    name: 'FMCG & Consumer',
    icon: '🛒',
    sentiment: 55,
    trend: 'flat',
    trendStrength: 1,
    keyDriver: 'Rural recovery signs; palm oil correction helps margins',
    change24h: +0.5,
    stocks: ['HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'DABUR'],
    globalExposure: 'Global commodity prices impact input costs',
  },
  {
    id: 'realestate',
    name: 'Real Estate & Infra',
    icon: '🏗️',
    sentiment: 68,
    trend: 'up',
    trendStrength: 1,
    keyDriver: 'Residential demand strong in tier-2 cities; govt infra push',
    change24h: +1.9,
    stocks: ['DLF', 'GODREJPROP', 'OBEROIRLTY', 'PRESTIGE', 'BRIGADE'],
    globalExposure: 'Foreign PE investment in Indian real estate rising',
  },
];

export const DEMO_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'OPEC+ extends oil production cuts through Q3, Brent crude jumps 3%',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    summary: 'OPEC+ has agreed to extend voluntary oil production cuts of 2.2 million barrels per day through the third quarter, pushing Brent crude above $84 per barrel. Indian oil marketing companies may face margin pressure.',
    sentiment: 0.6,
    sentimentLabel: 'positive',
    relatedSectors: ['energy'],
    relatedStocks: ['RELIANCE', 'ONGC', 'BPCL', 'IOC'],
    category: 'global',
    impactLevel: 'high',
  },
  {
    id: '2',
    title: 'India defense exports cross ₹21,000 crore; HAL gets $4.2B new orders',
    source: 'Economic Times',
    url: '#',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    summary: 'India\'s defense exports have reached a record high, with HAL securing new orders worth $4.2 billion from Southeast Asian and Middle Eastern countries. BEL also reports strong order pipeline.',
    sentiment: 0.85,
    sentimentLabel: 'positive',
    relatedSectors: ['defense'],
    relatedStocks: ['HAL', 'BEL', 'MAZAGON'],
    category: 'financial',
    impactLevel: 'high',
  },
  {
    id: '3',
    title: 'RBI keeps repo rate unchanged at 6.5%; signals cautious stance on inflation',
    source: 'MoneyControl',
    url: '#',
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    summary: 'The Reserve Bank of India maintained its repo rate at 6.5% for the eighth consecutive time, citing persistent food inflation risks. Banking stocks showed mixed reaction with large-caps holding steady.',
    sentiment: 0.1,
    sentimentLabel: 'neutral',
    relatedSectors: ['banking', 'realestate'],
    relatedStocks: ['HDFCBANK', 'SBIN', 'ICICIBANK', 'DLF'],
    category: 'policy',
    impactLevel: 'high',
  },
  {
    id: '4',
    title: 'Tata Motors EV sales surge 45% in June; Nexon EV crosses 1 lakh milestone',
    source: 'LiveMint',
    url: '#',
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    summary: 'Tata Motors reports a 45% year-on-year increase in EV sales, with the Nexon EV crossing the 1 lakh cumulative sales mark. The company plans to launch 3 new EV models in the next 6 months.',
    sentiment: 0.75,
    sentimentLabel: 'positive',
    relatedSectors: ['ev', 'auto'],
    relatedStocks: ['TATAMOTORS', 'EXIDEIND', 'KPITTECH'],
    category: 'earnings',
    impactLevel: 'medium',
  },
  {
    id: '5',
    title: 'Gold hits all-time high at ₹74,500/10g as geopolitical tensions escalate',
    source: 'NDTV Profit',
    url: '#',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    summary: 'Gold prices in India have touched a new all-time high amid escalating geopolitical tensions in Eastern Europe and the Middle East. Titan and jewellery stocks rally on increased consumer interest.',
    sentiment: 0.7,
    sentimentLabel: 'positive',
    relatedSectors: ['gold'],
    relatedStocks: ['TITAN', 'MUTHOOTFIN', 'KALYANFIN', 'SENCO'],
    category: 'geopolitical',
    impactLevel: 'high',
  },
  {
    id: '6',
    title: 'US tech layoffs continue; Infosys and TCS face deal pipeline delays',
    source: 'Business Standard',
    url: '#',
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    summary: 'Major US tech companies continue downsizing, leading to delays in outsourcing deal pipelines for Indian IT majors. TCS and Infosys both guided for cautious Q2 outlook, weighing on sector sentiment.',
    sentiment: -0.5,
    sentimentLabel: 'negative',
    relatedSectors: ['it'],
    relatedStocks: ['TCS', 'INFY', 'WIPRO', 'HCLTECH'],
    category: 'global',
    impactLevel: 'medium',
  },
  {
    id: '7',
    title: 'Adani Green commissions 2GW solar plant in Rajasthan; largest in India',
    source: 'Economic Times',
    url: '#',
    publishedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    summary: 'Adani Green Energy has commissioned the largest single-location solar plant in India at 2GW capacity in Rajasthan. The project positions India closer to its 500GW renewable energy target by 2030.',
    sentiment: 0.8,
    sentimentLabel: 'positive',
    relatedSectors: ['power', 'energy'],
    relatedStocks: ['ADANIGREEN', 'TATAPOWER', 'NTPC'],
    category: 'financial',
    impactLevel: 'medium',
  },
  {
    id: '8',
    title: 'China steel output falls 5%; Indian steelmakers eye export opportunities',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    summary: 'China\'s steel production has dropped 5% amid property sector downturn, creating potential export opportunities for Indian steelmakers. However, global oversupply concerns continue to weigh on prices.',
    sentiment: -0.2,
    sentimentLabel: 'neutral',
    relatedSectors: ['metals'],
    relatedStocks: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO'],
    category: 'global',
    impactLevel: 'medium',
  },
  {
    id: '9',
    title: 'FDA issues warning letter to Sun Pharma\'s Halol facility',
    source: 'MoneyControl',
    url: '#',
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    summary: 'The US FDA has issued a warning letter to Sun Pharmaceuticals\' Halol manufacturing facility citing GMP violations. The stock fell 3.5% in early trade, dragging pharma sector sentiment lower.',
    sentiment: -0.7,
    sentimentLabel: 'negative',
    relatedSectors: ['pharma'],
    relatedStocks: ['SUNPHARMA', 'CIPLA', 'DRREDDY'],
    category: 'financial',
    impactLevel: 'high',
  },
  {
    id: '10',
    title: 'Monsoon forecast upgraded; rural auto demand expected to surge',
    source: 'LiveMint',
    url: '#',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    summary: 'IMD has upgraded its monsoon forecast to "above normal" at 106% of LPA. This is expected to boost agricultural income and drive rural demand for two-wheelers and small cars in H2.',
    sentiment: 0.65,
    sentimentLabel: 'positive',
    relatedSectors: ['auto', 'fmcg'],
    relatedStocks: ['MARUTI', 'HEROMOTOCO', 'BAJAJ-AUTO', 'HINDUNILVR'],
    category: 'policy',
    impactLevel: 'medium',
  },
];

export const DEMO_GEOPOLITICAL_EVENTS: GeopoliticalEvent[] = [
  {
    id: 'geo1',
    region: 'Middle East',
    title: 'Red Sea shipping disruptions continue; Houthi attacks on cargo vessels',
    severity: 'hot',
    impactedSectors: ['energy', 'gold', 'defense'],
    lat: 15.5,
    lng: 42.0,
    description: 'Ongoing Houthi attacks on commercial vessels in the Red Sea are disrupting global shipping routes, adding 10-14 days to Europe-Asia trade. Crude oil and shipping costs rising.',
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'geo2',
    region: 'Russia-Ukraine',
    title: 'Russia-Ukraine conflict intensifies; sanctions tightened on energy trade',
    severity: 'hot',
    impactedSectors: ['energy', 'metals', 'gold', 'defense'],
    lat: 48.5,
    lng: 35.0,
    description: 'New Western sanctions on Russian oil exports are expected to tighten global crude supply. India continues to import discounted Russian crude, benefiting refinery margins.',
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'geo3',
    region: 'USA',
    title: 'Fed signals potential rate cut in September; dollar weakens',
    severity: 'watch',
    impactedSectors: ['it', 'banking', 'gold', 'pharma'],
    lat: 38.9,
    lng: -77.0,
    description: 'Federal Reserve Chair signals openness to rate cuts, weakening the US dollar. This is positive for gold (safe haven) and may boost FII flows into Indian equities.',
    date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'geo4',
    region: 'China',
    title: 'China property crisis deepens; Country Garden misses bond payment',
    severity: 'watch',
    impactedSectors: ['metals', 'auto', 'ev'],
    lat: 35.0,
    lng: 115.0,
    description: 'China\'s real estate sector continues to struggle with Country Garden missing another bond payment. This reduces demand for steel, copper, and construction materials, impacting Indian metal exporters.',
    date: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'geo5',
    region: 'India',
    title: 'India-Canada diplomatic tensions ease; trade talks resume',
    severity: 'calm',
    impactedSectors: ['it', 'pharma'],
    lat: 28.6,
    lng: 77.2,
    description: 'India and Canada have agreed to resume diplomatic engagement and trade discussions. This eases concerns for Indian tech companies with Canadian operations.',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_MARKET_OVERVIEW: MarketOverview = {
  overallSentiment: 64,
  marketStatus: 'closed',
  nifty50: { value: 24178.50, change: 156.30, changePercent: 0.65 },
  sensex: { value: 79468.25, change: 498.75, changePercent: 0.63 },
  topGainers: [],
  topLosers: [],
  biggestSentimentMovers: [],
};

// Sentiment history for sparkline charts (last 7 days)
export const DEMO_SENTIMENT_HISTORY: Record<string, number[]> = {
  energy: [62, 65, 68, 70, 69, 72, 74],
  power: [75, 76, 78, 77, 80, 79, 82],
  auto: [58, 60, 62, 61, 63, 64, 65],
  gold: [70, 72, 71, 74, 75, 76, 78],
  ev: [64, 66, 68, 67, 69, 70, 71],
  banking: [60, 59, 61, 58, 57, 59, 58],
  it: [55, 54, 53, 52, 53, 52, 52],
  pharma: [52, 50, 48, 47, 46, 46, 45],
  defense: [78, 79, 80, 82, 83, 84, 85],
  metals: [50, 48, 47, 45, 44, 43, 42],
  fmcg: [54, 55, 54, 55, 56, 55, 55],
  realestate: [64, 65, 66, 67, 67, 68, 68],
};
