// Curated list of popular Indian mutual funds with AMFI scheme codes
// Covers major fund houses and categories: Large Cap, Mid Cap, Small Cap, Flexi Cap, ELSS, Index, Hybrid

export interface MutualFundMeta {
  schemeCode: number;
  name: string;
  shortName: string;
  fundHouse: string;
  category: 'Large Cap' | 'Mid Cap' | 'Small Cap' | 'Flexi Cap' | 'ELSS' | 'Index' | 'Hybrid' | 'Debt' | 'Sectoral';
  planType: 'Direct' | 'Regular';
  risk: 'Low' | 'Moderate' | 'High' | 'Very High';
  // Top holdings (manually curated for major funds)
  topHoldings?: { name: string; weight: number }[];
}

export const CURATED_FUNDS: MutualFundMeta[] = [
  // ─── Large Cap ──────────────────────────────────────
  {
    schemeCode: 119598,
    name: 'SBI Large Cap Fund - Direct Plan - Growth',
    shortName: 'SBI Large Cap',
    fundHouse: 'SBI Mutual Fund',
    category: 'Large Cap',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'HDFC Bank', weight: 9.2 },
      { name: 'ICICI Bank', weight: 7.8 },
      { name: 'Reliance Industries', weight: 7.1 },
      { name: 'Infosys', weight: 5.9 },
      { name: 'TCS', weight: 5.3 },
      { name: 'L&T', weight: 4.8 },
      { name: 'Bharti Airtel', weight: 4.1 },
      { name: 'ITC', weight: 3.5 },
      { name: 'Axis Bank', weight: 3.2 },
      { name: 'HUL', weight: 2.9 },
    ],
  },
  {
    schemeCode: 120505,
    name: 'Mirae Asset Large Cap Fund - Direct Plan - Growth',
    shortName: 'Mirae Large Cap',
    fundHouse: 'Mirae Asset Mutual Fund',
    category: 'Large Cap',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'HDFC Bank', weight: 10.1 },
      { name: 'ICICI Bank', weight: 8.5 },
      { name: 'Infosys', weight: 6.8 },
      { name: 'Reliance Industries', weight: 6.2 },
      { name: 'TCS', weight: 5.4 },
      { name: 'Bharti Airtel', weight: 4.9 },
      { name: 'L&T', weight: 4.3 },
      { name: 'SBI', weight: 3.7 },
      { name: 'Axis Bank', weight: 3.4 },
      { name: 'Kotak Mahindra Bank', weight: 2.8 },
    ],
  },
  {
    schemeCode: 120503,
    name: 'Axis Bluechip Fund - Direct Plan - Growth',
    shortName: 'Axis Bluechip',
    fundHouse: 'Axis Mutual Fund',
    category: 'Large Cap',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'Bajaj Finance', weight: 8.4 },
      { name: 'HDFC Bank', weight: 7.9 },
      { name: 'TCS', weight: 6.2 },
      { name: 'Infosys', weight: 5.7 },
      { name: 'Avenue Supermarts', weight: 4.8 },
      { name: 'ICICI Bank', weight: 4.5 },
      { name: 'Reliance Industries', weight: 4.1 },
      { name: 'Titan', weight: 3.6 },
      { name: 'HUL', weight: 3.3 },
      { name: 'Asian Paints', weight: 2.9 },
    ],
  },

  // ─── Mid Cap ────────────────────────────────────────
  {
    schemeCode: 119062,
    name: 'HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth',
    shortName: 'HDFC Midcap Opp',
    fundHouse: 'HDFC Mutual Fund',
    category: 'Mid Cap',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'Indian Hotels', weight: 4.2 },
      { name: 'Max Healthcare', weight: 3.8 },
      { name: 'Coforge', weight: 3.5 },
      { name: 'Persistent Systems', weight: 3.2 },
      { name: 'Escorts Kubota', weight: 2.9 },
      { name: 'Balkrishna Industries', weight: 2.7 },
      { name: 'Oberoi Realty', weight: 2.5 },
      { name: 'Sundaram Finance', weight: 2.3 },
      { name: 'Mphasis', weight: 2.1 },
      { name: 'Federal Bank', weight: 1.9 },
    ],
  },
  {
    schemeCode: 125497,
    name: 'Kotak Emerging Equity Fund - Direct Plan - Growth',
    shortName: 'Kotak Emerging',
    fundHouse: 'Kotak Mutual Fund',
    category: 'Mid Cap',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'Persistent Systems', weight: 3.9 },
      { name: 'Supreme Industries', weight: 3.4 },
      { name: 'Cummins India', weight: 3.1 },
      { name: 'Dixon Technologies', weight: 2.8 },
      { name: 'Coforge', weight: 2.6 },
      { name: 'The Phoenix Mills', weight: 2.4 },
      { name: 'Voltas', weight: 2.2 },
      { name: 'Max Financial', weight: 2.0 },
      { name: 'Emami', weight: 1.8 },
      { name: 'CG Power', weight: 1.7 },
    ],
  },

  // ─── Small Cap ──────────────────────────────────────
  {
    schemeCode: 125354,
    name: 'SBI Small Cap Fund - Direct Plan - Growth',
    shortName: 'SBI Small Cap',
    fundHouse: 'SBI Mutual Fund',
    category: 'Small Cap',
    planType: 'Direct',
    risk: 'Very High',
    topHoldings: [
      { name: 'IIFL Finance', weight: 3.1 },
      { name: 'Finolex Industries', weight: 2.8 },
      { name: 'Blue Star', weight: 2.5 },
      { name: 'Chalet Hotels', weight: 2.3 },
      { name: 'Kalpataru Projects', weight: 2.1 },
      { name: 'Elgi Equipments', weight: 1.9 },
      { name: 'KPIT Technologies', weight: 1.7 },
      { name: 'Carborundum Universal', weight: 1.6 },
      { name: 'EIH', weight: 1.5 },
      { name: 'Sheela Foam', weight: 1.4 },
    ],
  },
  {
    schemeCode: 130503,
    name: 'Nippon India Small Cap Fund - Direct Plan - Growth',
    shortName: 'Nippon Small Cap',
    fundHouse: 'Nippon India Mutual Fund',
    category: 'Small Cap',
    planType: 'Direct',
    risk: 'Very High',
    topHoldings: [
      { name: 'KPIT Technologies', weight: 2.6 },
      { name: 'Multi Commodity Exchange', weight: 2.3 },
      { name: 'Tube Investments', weight: 2.1 },
      { name: 'Karur Vysya Bank', weight: 1.9 },
      { name: 'Affle India', weight: 1.7 },
      { name: 'Ratnamani Metals', weight: 1.6 },
      { name: 'RITES', weight: 1.5 },
      { name: 'Cyient', weight: 1.4 },
      { name: 'Radico Khaitan', weight: 1.3 },
      { name: 'Sonata Software', weight: 1.2 },
    ],
  },

  // ─── Flexi Cap ──────────────────────────────────────
  {
    schemeCode: 122639,
    name: 'Parag Parikh Flexi Cap Fund - Direct Plan - Growth',
    shortName: 'PPFAS Flexi Cap',
    fundHouse: 'PPFAS Mutual Fund',
    category: 'Flexi Cap',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'HDFC Bank', weight: 7.2 },
      { name: 'ICICI Bank', weight: 5.8 },
      { name: 'Bajaj Holdings', weight: 4.6 },
      { name: 'ITC', weight: 4.3 },
      { name: 'Power Grid Corp', weight: 3.8 },
      { name: 'Coal India', weight: 3.5 },
      { name: 'Alphabet Inc', weight: 3.2 },
      { name: 'Microsoft', weight: 2.9 },
      { name: 'Amazon', weight: 2.6 },
      { name: 'HCL Tech', weight: 2.4 },
    ],
  },
  {
    schemeCode: 119364,
    name: 'HDFC Flexi Cap Fund - Direct Plan - Growth',
    shortName: 'HDFC Flexi Cap',
    fundHouse: 'HDFC Mutual Fund',
    category: 'Flexi Cap',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'ICICI Bank', weight: 9.5 },
      { name: 'HDFC Bank', weight: 7.8 },
      { name: 'Axis Bank', weight: 5.2 },
      { name: 'SBI', weight: 4.7 },
      { name: 'Cipla', weight: 3.9 },
      { name: 'Bharti Airtel', weight: 3.6 },
      { name: 'Coal India', weight: 3.3 },
      { name: 'Maruti Suzuki', weight: 3.0 },
      { name: 'L&T', weight: 2.8 },
      { name: 'HCL Tech', weight: 2.5 },
    ],
  },

  // ─── ELSS (Tax Saving) ─────────────────────────────
  {
    schemeCode: 120847,
    name: 'Mirae Asset ELSS Tax Saver Fund - Direct Plan - Growth',
    shortName: 'Mirae ELSS',
    fundHouse: 'Mirae Asset Mutual Fund',
    category: 'ELSS',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'HDFC Bank', weight: 8.7 },
      { name: 'ICICI Bank', weight: 7.1 },
      { name: 'Reliance Industries', weight: 5.9 },
      { name: 'Infosys', weight: 5.2 },
      { name: 'Bharti Airtel', weight: 4.4 },
      { name: 'TCS', weight: 4.0 },
      { name: 'L&T', weight: 3.5 },
      { name: 'SBI', weight: 3.2 },
      { name: 'Axis Bank', weight: 2.8 },
      { name: 'Mahindra & Mahindra', weight: 2.5 },
    ],
  },
  {
    schemeCode: 119775,
    name: 'Axis ELSS Tax Saver Fund - Direct Plan - Growth',
    shortName: 'Axis ELSS',
    fundHouse: 'Axis Mutual Fund',
    category: 'ELSS',
    planType: 'Direct',
    risk: 'High',
    topHoldings: [
      { name: 'Bajaj Finance', weight: 7.8 },
      { name: 'HDFC Bank', weight: 6.5 },
      { name: 'TCS', weight: 5.8 },
      { name: 'Infosys', weight: 5.1 },
      { name: 'ICICI Bank', weight: 4.5 },
      { name: 'Avenue Supermarts', weight: 3.9 },
      { name: 'Cholamandalam Inv', weight: 3.4 },
      { name: 'Titan', weight: 3.1 },
      { name: 'Divi\'s Labs', weight: 2.7 },
      { name: 'Asian Paints', weight: 2.4 },
    ],
  },

  // ─── Index Funds ────────────────────────────────────
  {
    schemeCode: 120716,
    name: 'UTI Nifty 50 Index Fund - Direct Plan - Growth',
    shortName: 'UTI Nifty 50 Index',
    fundHouse: 'UTI Mutual Fund',
    category: 'Index',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'HDFC Bank', weight: 12.8 },
      { name: 'Reliance Industries', weight: 9.5 },
      { name: 'ICICI Bank', weight: 8.2 },
      { name: 'Infosys', weight: 6.1 },
      { name: 'TCS', weight: 4.8 },
      { name: 'Bharti Airtel', weight: 4.2 },
      { name: 'L&T', weight: 3.9 },
      { name: 'ITC', weight: 3.6 },
      { name: 'SBI', weight: 3.3 },
      { name: 'Axis Bank', weight: 2.9 },
    ],
  },
  {
    schemeCode: 140679,
    name: 'Motilal Oswal Nifty Midcap 150 Index Fund - Direct Plan - Growth',
    shortName: 'MON Midcap 150',
    fundHouse: 'Motilal Oswal Mutual Fund',
    category: 'Index',
    planType: 'Direct',
    risk: 'High',
  },

  // ─── Hybrid ─────────────────────────────────────────
  {
    schemeCode: 119551,
    name: 'ICICI Prudential Equity & Debt Fund - Direct Plan - Growth',
    shortName: 'ICICI Equity & Debt',
    fundHouse: 'ICICI Prudential Mutual Fund',
    category: 'Hybrid',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'NTPC', weight: 5.1 },
      { name: 'HDFC Bank', weight: 4.8 },
      { name: 'ICICI Bank', weight: 4.3 },
      { name: 'Reliance Industries', weight: 3.9 },
      { name: 'Infosys', weight: 3.5 },
      { name: 'GOI Securities', weight: 12.0 },
      { name: 'SBI', weight: 3.1 },
      { name: 'L&T', weight: 2.8 },
      { name: 'Bharti Airtel', weight: 2.5 },
      { name: 'Maruti Suzuki', weight: 2.2 },
    ],
  },
  {
    schemeCode: 119568,
    name: 'SBI Equity Hybrid Fund - Direct Plan - Growth',
    shortName: 'SBI Equity Hybrid',
    fundHouse: 'SBI Mutual Fund',
    category: 'Hybrid',
    planType: 'Direct',
    risk: 'Moderate',
    topHoldings: [
      { name: 'HDFC Bank', weight: 6.8 },
      { name: 'ICICI Bank', weight: 5.4 },
      { name: 'Infosys', weight: 4.7 },
      { name: 'Reliance Industries', weight: 4.2 },
      { name: 'TCS', weight: 3.8 },
      { name: 'GOI Securities', weight: 15.0 },
      { name: 'L&T', weight: 3.1 },
      { name: 'Bharti Airtel', weight: 2.7 },
      { name: 'ITC', weight: 2.4 },
      { name: 'Axis Bank', weight: 2.1 },
    ],
  },

  // ─── Sectoral ───────────────────────────────────────
  {
    schemeCode: 120837,
    name: 'ICICI Prudential Technology Fund - Direct Plan - Growth',
    shortName: 'ICICI Tech Fund',
    fundHouse: 'ICICI Prudential Mutual Fund',
    category: 'Sectoral',
    planType: 'Direct',
    risk: 'Very High',
    topHoldings: [
      { name: 'Infosys', weight: 18.5 },
      { name: 'TCS', weight: 15.2 },
      { name: 'HCL Tech', weight: 8.9 },
      { name: 'Wipro', weight: 6.4 },
      { name: 'Tech Mahindra', weight: 5.7 },
      { name: 'LTIMindtree', weight: 4.8 },
      { name: 'Persistent Systems', weight: 3.9 },
      { name: 'Mphasis', weight: 3.2 },
      { name: 'Coforge', weight: 2.8 },
      { name: 'KPIT Technologies', weight: 2.4 },
    ],
  },
  {
    schemeCode: 120175,
    name: 'SBI Banking & Financial Services Fund - Direct Plan - Growth',
    shortName: 'SBI Banking Fund',
    fundHouse: 'SBI Mutual Fund',
    category: 'Sectoral',
    planType: 'Direct',
    risk: 'Very High',
    topHoldings: [
      { name: 'HDFC Bank', weight: 22.1 },
      { name: 'ICICI Bank', weight: 15.8 },
      { name: 'Axis Bank', weight: 8.9 },
      { name: 'SBI', weight: 7.5 },
      { name: 'Kotak Mahindra Bank', weight: 6.2 },
      { name: 'Bajaj Finance', weight: 5.4 },
      { name: 'IndusInd Bank', weight: 3.8 },
      { name: 'Bajaj Finserv', weight: 3.1 },
      { name: 'Federal Bank', weight: 2.6 },
      { name: 'HDFC Life', weight: 2.3 },
    ],
  },
];

// Category colors for UI
export const CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Large Cap': { bg: 'rgba(59,130,246,0.12)', text: '#3b82f6', border: 'rgba(59,130,246,0.25)' },
  'Mid Cap': { bg: 'rgba(168,85,247,0.12)', text: '#a855f7', border: 'rgba(168,85,247,0.25)' },
  'Small Cap': { bg: 'rgba(249,115,22,0.12)', text: '#f97316', border: 'rgba(249,115,22,0.25)' },
  'Flexi Cap': { bg: 'rgba(20,184,166,0.12)', text: '#14b8a6', border: 'rgba(20,184,166,0.25)' },
  'ELSS': { bg: 'rgba(16,185,129,0.12)', text: '#10b981', border: 'rgba(16,185,129,0.25)' },
  'Index': { bg: 'rgba(99,102,241,0.12)', text: '#6366f1', border: 'rgba(99,102,241,0.25)' },
  'Hybrid': { bg: 'rgba(236,72,153,0.12)', text: '#ec4899', border: 'rgba(236,72,153,0.25)' },
  'Debt': { bg: 'rgba(107,114,128,0.12)', text: '#6b7280', border: 'rgba(107,114,128,0.25)' },
  'Sectoral': { bg: 'rgba(245,158,11,0.12)', text: '#f59e0b', border: 'rgba(245,158,11,0.25)' },
};

export const RISK_COLORS: Record<string, string> = {
  'Low': '#10b981',
  'Moderate': '#f59e0b',
  'High': '#f97316',
  'Very High': '#ef4444',
};
