// Sector and Stock mapping for Indian markets
// Priority: Energy, Power, Auto, Gold, EV + others

export const SECTORS = {
  energy: {
    id: 'energy',
    name: 'Energy & Oil',
    icon: '⛽',
    stocks: ['RELIANCE', 'ONGC', 'IOC', 'BPCL', 'GAIL', 'HINDPETRO', 'PETRONET', 'OIL', 'MRPL', 'CASTROLIND'],
    globalExposure: 'Crude oil prices, OPEC decisions, Middle East tensions, US shale production',
    keywords: ['oil', 'crude', 'petroleum', 'OPEC', 'energy', 'gas', 'refinery', 'fuel', 'diesel', 'petrol'],
  },
  power: {
    id: 'power',
    name: 'Power & Utilities',
    icon: '⚡',
    stocks: ['NTPC', 'POWERGRID', 'TATAPOWER', 'ADANIGREEN', 'JSWENERGY', 'NHPC', 'SJVN', 'IREDA', 'CESC', 'TORNTPOWER'],
    globalExposure: 'Coal prices, renewable energy policies, monsoon impact, govt subsidies',
    keywords: ['power', 'electricity', 'solar', 'wind', 'renewable', 'grid', 'thermal', 'hydro', 'green energy'],
  },
  auto: {
    id: 'auto',
    name: 'Automobile',
    icon: '🚗',
    stocks: ['MARUTI', 'TATAMOTORS', 'M&M', 'BAJAJ-AUTO', 'HEROMOTOCO', 'EICHERMOT', 'ASHOKLEY', 'BHARATFORG', 'BOSCHLTD', 'MOTHERSON', 'TMCV'],
    globalExposure: 'Steel prices, semiconductor supply, fuel prices, consumer demand, monsoon',
    keywords: ['auto', 'car', 'vehicle', 'EV', 'electric vehicle', 'automobile', 'motorcycle', 'scooter'],
  },
  gold: {
    id: 'gold',
    name: 'Gold & Precious Metals',
    icon: '🥇',
    stocks: ['TITAN', 'MUTHOOTFIN', 'MANAPPURAM', 'RAJESHEXPO', 'GOLDBEES', 'KALYANFIN', 'SENCO', 'PNGJL', 'TBZJEWEL'],
    globalExposure: 'US Dollar strength, Fed rates, geopolitical uncertainty, inflation hedging',
    keywords: ['gold', 'silver', 'precious', 'jewellery', 'jewelry', 'bullion', 'sovereign gold'],
  },
  ev: {
    id: 'ev',
    name: 'Electric Vehicles',
    icon: '🔋',
    stocks: ['TATAMOTORS', 'M&M', 'OLECTRA', 'EXIDEIND', 'AMARAJABAT', 'TATAELXSI', 'KPITTECH', 'GREAVESCOT', 'HAPPSTMNDS', 'TMCV'],
    globalExposure: 'Lithium prices, battery tech breakthroughs, govt EV policies, charging infra',
    keywords: ['EV', 'electric vehicle', 'battery', 'lithium', 'charging', 'tesla', 'hybrid', 'BEV'],
  },
  banking: {
    id: 'banking',
    name: 'Banking & Finance',
    icon: '🏦',
    stocks: ['HDFCBANK', 'ICICIBANK', 'SBIN', 'KOTAKBANK', 'AXISBANK', 'INDUSINDBK', 'BANDHANBNK', 'PNB', 'BANKBARODA', 'IDFCFIRSTB'],
    globalExposure: 'RBI repo rate, US Fed decisions, NPA levels, credit growth, foreign investments',
    keywords: ['bank', 'RBI', 'interest rate', 'loan', 'credit', 'NPA', 'deposit', 'monetary policy'],
  },
  it: {
    id: 'it',
    name: 'IT & Technology',
    icon: '💻',
    stocks: ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM', 'LTIM', 'PERSISTENT', 'COFORGE', 'MPHASIS', 'CYIENT'],
    globalExposure: 'US tech spending, rupee-dollar exchange, visa policies, AI disruption',
    keywords: ['IT', 'software', 'technology', 'digital', 'cloud', 'AI', 'outsourcing', 'tech'],
  },
  pharma: {
    id: 'pharma',
    name: 'Pharma & Healthcare',
    icon: '💊',
    stocks: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'DIVISLAB', 'APOLLOHOSP', 'BIOCON', 'LUPIN', 'AUROPHARMA', 'TORNTPHARM', 'ALKEM'],
    globalExposure: 'FDA approvals, US generic drug pricing, pandemic risks, API supply chain',
    keywords: ['pharma', 'drug', 'FDA', 'medicine', 'hospital', 'healthcare', 'vaccine', 'generic'],
  },
  defense: {
    id: 'defense',
    name: 'Defense & Aerospace',
    icon: '🛡️',
    stocks: ['HAL', 'BEL', 'BHEL', 'SOLARINDS', 'COCHINSHIP', 'MAZAGON', 'GRSE', 'BDL', 'DATAPATTR', 'PARAS'],
    globalExposure: 'Border tensions, defense budget, Make in India orders, geopolitical conflicts',
    keywords: ['defense', 'defence', 'military', 'weapon', 'army', 'navy', 'air force', 'missile', 'border'],
  },
  metals: {
    id: 'metals',
    name: 'Metals & Mining',
    icon: '⛏️',
    stocks: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL', 'COALINDIA', 'NMDC', 'SAIL', 'NATIONALUM', 'JINDALSTEL', 'MOIL'],
    globalExposure: 'China demand, global steel/aluminum prices, infrastructure spending, trade wars',
    keywords: ['steel', 'metal', 'mining', 'aluminum', 'copper', 'iron', 'ore', 'coal', 'zinc'],
  },
  fmcg: {
    id: 'fmcg',
    name: 'FMCG & Consumer',
    icon: '🛒',
    stocks: ['HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'DABUR', 'MARICO', 'GODREJCP', 'COLPAL', 'EMAMILTD', 'TATACONSUM'],
    globalExposure: 'Rural demand, monsoon season, palm oil prices, consumer inflation',
    keywords: ['FMCG', 'consumer', 'food', 'beverage', 'retail', 'grocery', 'personal care'],
  },
  realestate: {
    id: 'realestate',
    name: 'Real Estate & Infra',
    icon: '🏗️',
    stocks: ['DLF', 'GODREJPROP', 'OBEROIRLTY', 'PRESTIGE', 'BRIGADE', 'LTIM', 'LNTFH', 'IRB', 'NBCC', 'LODHA'],
    globalExposure: 'Interest rates, urbanization, govt housing schemes, cement/steel prices',
    keywords: ['real estate', 'property', 'housing', 'construction', 'infrastructure', 'cement'],
  },
};

// All unique stocks across sectors
export const ALL_STOCKS: { symbol: string; name: string; sector: string }[] = [
  { symbol: '360ONE', name: '360 ONE WAM Ltd.', sector: 'banking' },
  { symbol: '3MINDIA', name: '3M India Ltd.', sector: 'general' },
  { symbol: 'AADHARHFC', name: 'Aadhar Housing Finance Ltd.', sector: 'banking' },
  { symbol: 'AARTIIND', name: 'Aarti Industries Ltd.', sector: 'energy' },
  { symbol: 'AAVAS', name: 'Aavas Financiers Ltd.', sector: 'banking' },
  { symbol: 'ABB', name: 'ABB India Ltd.', sector: 'it' },
  { symbol: 'ABBOTINDIA', name: 'Abbott India Ltd.', sector: 'pharma' },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital Ltd.', sector: 'banking' },
  { symbol: 'ABDL', name: 'Allied Blenders and Distillers Ltd.', sector: 'fmcg' },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion and Retail Ltd.', sector: 'general' },
  { symbol: 'ABLBL', name: 'Aditya Birla Lifestyle Brands Ltd.', sector: 'general' },
  { symbol: 'ABREL', name: 'Aditya Birla Real Estate Ltd.', sector: 'realestate' },
  { symbol: 'ABSLAMC', name: 'Aditya Birla Sun Life AMC Ltd.', sector: 'banking' },
  { symbol: 'ACC', name: 'ACC Ltd.', sector: 'realestate' },
  { symbol: 'ACE', name: 'Action Construction Equipment Ltd.', sector: 'it' },
  { symbol: 'ACMESOLAR', name: 'ACME Solar Holdings Ltd.', sector: 'power' },
  { symbol: 'ACUTAAS', name: 'Acutaas Chemicals Ltd.', sector: 'pharma' },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions Ltd.', sector: 'power' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd.', sector: 'metals' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd.', sector: 'power' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd.', sector: 'general' },
  { symbol: 'ADANIPOWER', name: 'Adani Power Ltd.', sector: 'power' },
  { symbol: 'AEGISLOG', name: 'Aegis Logistics Ltd.', sector: 'energy' },
  { symbol: 'AEGISVOPAK', name: 'Aegis Vopak Terminals Ltd.', sector: 'energy' },
  { symbol: 'AFCONS', name: 'Afcons Infrastructure Ltd.', sector: 'realestate' },
  { symbol: 'AFFLE', name: 'Affle 3i Ltd.', sector: 'it' },
  { symbol: 'AIAENG', name: 'AIA Engineering Ltd.', sector: 'it' },
  { symbol: 'AIIL', name: 'Authum Investment & Infrastructure Ltd.', sector: 'banking' },
  { symbol: 'AJANTPHARM', name: 'Ajanta Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'AMBER', name: 'Amber Enterprises India Ltd.', sector: 'fmcg' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd.', sector: 'realestate' },
  { symbol: 'ANANDRATHI', name: 'Anand Rathi Wealth Ltd.', sector: 'banking' },
  { symbol: 'ANANTRAJ', name: 'Anant Raj Ltd.', sector: 'realestate' },
  { symbol: 'ANGELONE', name: 'Angel One Ltd.', sector: 'banking' },
  { symbol: 'ANTHEM', name: 'Anthem Biosciences Ltd.', sector: 'pharma' },
  { symbol: 'ANURAS', name: 'Anupam Rasayan India Ltd.', sector: 'energy' },
  { symbol: 'APARINDS', name: 'Apar Industries Ltd.', sector: 'it' },
  { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes Ltd.', sector: 'it' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd.', sector: 'pharma' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd.', sector: 'auto' },
  { symbol: 'APTUS', name: 'Aptus Value Housing Finance India Ltd.', sector: 'banking' },
  { symbol: 'ARE&M', name: 'Amara Raja Energy & Mobility Ltd.', sector: 'auto' },
  { symbol: 'ASAHIINDIA', name: 'Asahi India Glass Ltd.', sector: 'auto' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd.', sector: 'it' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd.', sector: 'fmcg' },
  { symbol: 'ASTERDM', name: 'Aster DM Healthcare Ltd.', sector: 'pharma' },
  { symbol: 'ASTRAL', name: 'Astral Ltd.', sector: 'it' },
  { symbol: 'ATGL', name: 'Adani Total Gas Ltd.', sector: 'energy' },
  { symbol: 'ATHERENERG', name: 'Ather Energy Ltd.', sector: 'auto' },
  { symbol: 'ATUL', name: 'Atul Ltd.', sector: 'energy' },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank Ltd.', sector: 'banking' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.', sector: 'pharma' },
  { symbol: 'AWL', name: 'AWL Agri Business Ltd.', sector: 'fmcg' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd.', sector: 'banking' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd.', sector: 'auto' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.', sector: 'banking' },
  { symbol: 'BAJAJHFL', name: 'Bajaj Housing Finance Ltd.', sector: 'banking' },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment Ltd.', sector: 'banking' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd.', sector: 'banking' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries Ltd.', sector: 'auto' },
  { symbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills Ltd.', sector: 'fmcg' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd.', sector: 'banking' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'banking' },
  { symbol: 'BANKINDIA', name: 'Bank of India', sector: 'banking' },
  { symbol: 'BATAINDIA', name: 'Bata India Ltd.', sector: 'fmcg' },
  { symbol: 'BAYERCROP', name: 'Bayer Cropscience Ltd.', sector: 'energy' },
  { symbol: 'BBTC', name: 'Bombay Burmah Trading Corporation Ltd.', sector: 'fmcg' },
  { symbol: 'BDL', name: 'Bharat Dynamics Ltd.', sector: 'defense' },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd.', sector: 'defense' },
  { symbol: 'BELRISE', name: 'Belrise Industries Ltd.', sector: 'auto' },
  { symbol: 'BEML', name: 'BEML Ltd.', sector: 'it' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India Ltd.', sector: 'fmcg' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd.', sector: 'auto' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd.', sector: 'it' },
  { symbol: 'BHARTIHEXA', name: 'Bharti Hexacom Ltd.', sector: 'it' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd.', sector: 'defense' },
  { symbol: 'BIKAJI', name: 'Bikaji Foods International Ltd.', sector: 'fmcg' },
  { symbol: 'BIOCON', name: 'Biocon Ltd.', sector: 'pharma' },
  { symbol: 'BLS', name: 'BLS International Services Ltd.', sector: 'general' },
  { symbol: 'BLUEDART', name: 'Blue Dart Express Ltd.', sector: 'general' },
  { symbol: 'BLUEJET', name: 'Blue Jet Healthcare Ltd.', sector: 'pharma' },
  { symbol: 'BLUESTARCO', name: 'Blue Star Ltd.', sector: 'fmcg' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd.', sector: 'auto' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd.', sector: 'energy' },
  { symbol: 'BRIGADE', name: 'Brigade Enterprises Ltd.', sector: 'realestate' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd.', sector: 'fmcg' },
  { symbol: 'BSE', name: 'BSE Ltd.', sector: 'banking' },
  { symbol: 'BSOFT', name: 'Birlasoft Ltd.', sector: 'it' },
  { symbol: 'CAMS', name: 'Computer Age Management Services Ltd.', sector: 'banking' },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'banking' },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes Ltd.', sector: 'banking' },
  { symbol: 'CANHLIFE', name: 'Canara HSBC Life Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'CAPLIPOINT', name: 'Caplin Point Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'CARBORUNIV', name: 'Carborundum Universal Ltd.', sector: 'it' },
  { symbol: 'CARTRADE', name: 'Cartrade Tech Ltd.', sector: 'general' },
  { symbol: 'CASTROLIND', name: 'Castrol India Ltd.', sector: 'energy' },
  { symbol: 'CCL', name: 'CCL Products (I) Ltd.', sector: 'fmcg' },
  { symbol: 'CDSL', name: 'Central Depository Services (India) Ltd.', sector: 'banking' },
  { symbol: 'CEATLTD', name: 'Ceat Ltd.', sector: 'auto' },
  { symbol: 'CEMPRO', name: 'Cemindia Projects Ltd.', sector: 'realestate' },
  { symbol: 'CENTRALBK', name: 'Central Bank of India', sector: 'banking' },
  { symbol: 'CESC', name: 'CESC Ltd.', sector: 'power' },
  { symbol: 'CGCL', name: 'Capri Global Capital Ltd.', sector: 'banking' },
  { symbol: 'CGPOWER', name: 'CG Power and Industrial Solutions Ltd.', sector: 'it' },
  { symbol: 'CHALET', name: 'Chalet Hotels Ltd.', sector: 'general' },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilizers & Chemicals Ltd.', sector: 'energy' },
  { symbol: 'CHENNPETRO', name: 'Chennai Petroleum Corporation Ltd.', sector: 'energy' },
  { symbol: 'CHOICEIN', name: 'Choice International Ltd.', sector: 'banking' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment and Finance Company Ltd.', sector: 'banking' },
  { symbol: 'CHOLAHLDNG', name: 'Cholamandalam Financial Holdings Ltd.', sector: 'banking' },
  { symbol: 'CIEINDIA', name: 'CIE Automotive India Ltd.', sector: 'auto' },
  { symbol: 'CIPLA', name: 'Cipla Ltd.', sector: 'pharma' },
  { symbol: 'CLEAN', name: 'Clean Science and Technology Ltd.', sector: 'energy' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd.', sector: 'energy' },
  { symbol: 'COCHINSHIP', name: 'Cochin Shipyard Ltd.', sector: 'defense' },
  { symbol: 'COFORGE', name: 'Coforge Ltd.', sector: 'it' },
  { symbol: 'COHANCE', name: 'Cohance Lifesciences Ltd.', sector: 'pharma' },
  { symbol: 'COLPAL', name: 'Colgate Palmolive (India) Ltd.', sector: 'fmcg' },
  { symbol: 'CONCOR', name: 'Container Corporation of India Ltd.', sector: 'general' },
  { symbol: 'CONCORDBIO', name: 'Concord Biotech Ltd.', sector: 'pharma' },
  { symbol: 'COROMANDEL', name: 'Coromandel International Ltd.', sector: 'energy' },
  { symbol: 'CPPLUS', name: 'Aditya Infotech Ltd.', sector: 'it' },
  { symbol: 'CRAFTSMAN', name: 'Craftsman Automation Ltd.', sector: 'auto' },
  { symbol: 'CREDITACC', name: 'CreditAccess Grameen Ltd.', sector: 'banking' },
  { symbol: 'CRISIL', name: 'CRISIL Ltd.', sector: 'banking' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals Ltd.', sector: 'fmcg' },
  { symbol: 'CUB', name: 'City Union Bank Ltd.', sector: 'banking' },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd.', sector: 'it' },
  { symbol: 'CYIENT', name: 'Cyient Ltd.', sector: 'it' },
  { symbol: 'DABUR', name: 'Dabur India Ltd.', sector: 'fmcg' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd.', sector: 'realestate' },
  { symbol: 'DATAPATTNS', name: 'Data Patterns (India) Ltd.', sector: 'it' },
  { symbol: 'DCMSHRIRAM', name: 'DCM Shriram Ltd.', sector: 'general' },
  { symbol: 'DEEPAKFERT', name: 'Deepak Fertilisers & Petrochemicals Corp. Ltd.', sector: 'energy' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.', sector: 'energy' },
  { symbol: 'DELHIVERY', name: 'Delhivery Ltd.', sector: 'general' },
  { symbol: 'DEVYANI', name: 'Devyani International Ltd.', sector: 'general' },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'DIXON', name: 'Dixon Technologies (India) Ltd.', sector: 'fmcg' },
  { symbol: 'DLF', name: 'DLF Ltd.', sector: 'realestate' },
  { symbol: 'DMART', name: 'Avenue Supermarts Ltd.', sector: 'general' },
  { symbol: 'DOMS', name: 'DOMS Industries Ltd.', sector: 'fmcg' },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'ECLERX', name: 'eClerx Services Ltd.', sector: 'general' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd.', sector: 'auto' },
  { symbol: 'EIDPARRY', name: 'E.I.D. Parry (India) Ltd.', sector: 'fmcg' },
  { symbol: 'EIHOTEL', name: 'EIH Ltd.', sector: 'general' },
  { symbol: 'ELECON', name: 'Elecon Engineering Co. Ltd.', sector: 'it' },
  { symbol: 'ELGIEQUIP', name: 'Elgi Equipments Ltd.', sector: 'it' },
  { symbol: 'EMAMILTD', name: 'Emami Ltd.', sector: 'fmcg' },
  { symbol: 'EMCURE', name: 'Emcure Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'EMMVEE', name: 'Emmvee Photovoltaic Power Ltd.', sector: 'it' },
  { symbol: 'ENDURANCE', name: 'Endurance Technologies Ltd.', sector: 'auto' },
  { symbol: 'ENGINERSIN', name: 'Engineers India Ltd.', sector: 'realestate' },
  { symbol: 'ENRIN', name: 'Siemens Energy India Ltd.', sector: 'it' },
  { symbol: 'ERIS', name: 'Eris Lifesciences Ltd.', sector: 'pharma' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota Ltd.', sector: 'it' },
  { symbol: 'ETERNAL', name: 'Eternal Ltd.', sector: 'general' },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd.', sector: 'ev' },
  { symbol: 'FACT', name: 'Fertilisers and Chemicals Travancore Ltd.', sector: 'energy' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank Ltd.', sector: 'banking' },
  { symbol: 'FINCABLES', name: 'Finolex Cables Ltd.', sector: 'it' },
  { symbol: 'FIRSTCRY', name: 'Brainbees Solutions Ltd.', sector: 'general' },
  { symbol: 'FIVESTAR', name: 'Five-Star Business Finance Ltd.', sector: 'banking' },
  { symbol: 'FLUOROCHEM', name: 'Gujarat Fluorochemicals Ltd.', sector: 'energy' },
  { symbol: 'FORCEMOT', name: 'Force Motors Ltd.', sector: 'auto' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare Ltd.', sector: 'pharma' },
  { symbol: 'FSL', name: 'Firstsource Solutions Ltd.', sector: 'general' },
  { symbol: 'GABRIEL', name: 'Gabriel India Ltd.', sector: 'auto' },
  { symbol: 'GAIL', name: 'GAIL (India) Ltd.', sector: 'energy' },
  { symbol: 'GALLANTT', name: 'Gallantt Ispat Ltd.', sector: 'it' },
  { symbol: 'GESHIP', name: 'Great Eastern Shipping Co. Ltd.', sector: 'general' },
  { symbol: 'GICRE', name: 'General Insurance Corporation of India', sector: 'banking' },
  { symbol: 'GILLETTE', name: 'Gillette India Ltd.', sector: 'fmcg' },
  { symbol: 'GLAND', name: 'Gland Pharma Ltd.', sector: 'pharma' },
  { symbol: 'GLAXO', name: 'Glaxosmithkline Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'GMDCLTD', name: 'Gujarat Mineral Development Corporation Ltd.', sector: 'metals' },
  { symbol: 'GMRAIRPORT', name: 'GMR Airports Ltd.', sector: 'general' },
  { symbol: 'GODFRYPHLP', name: 'Godfrey Phillips India Ltd.', sector: 'fmcg' },
  { symbol: 'GODIGIT', name: 'Go Digit General Insurance Ltd.', sector: 'banking' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd.', sector: 'fmcg' },
  { symbol: 'GODREJIND', name: 'Godrej Industries Ltd.', sector: 'general' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd.', sector: 'realestate' },
  { symbol: 'GPIL', name: 'Godawari Power & Ispat Ltd.', sector: 'it' },
  { symbol: 'GRANULES', name: 'Granules India Ltd.', sector: 'pharma' },
  { symbol: 'GRAPHITE', name: 'Graphite India Ltd.', sector: 'it' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd.', sector: 'realestate' },
  { symbol: 'GRAVITA', name: 'Gravita India Ltd.', sector: 'metals' },
  { symbol: 'GROWW', name: 'Billionbrains Garage Ventures Ltd.', sector: 'banking' },
  { symbol: 'GRSE', name: 'Garden Reach Shipbuilders & Engineers Ltd.', sector: 'defense' },
  { symbol: 'GVT&D', name: 'GE Vernova T&D India Ltd.', sector: 'it' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd.', sector: 'defense' },
  { symbol: 'HAVELLS', name: 'Havells India Ltd.', sector: 'fmcg' },
  { symbol: 'HBLENGINE', name: 'HBL Engineering Ltd.', sector: 'it' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd.', sector: 'it' },
  { symbol: 'HDBFS', name: 'HDB Financial Services Ltd.', sector: 'banking' },
  { symbol: 'HDFCAMC', name: 'HDFC Asset Management Company Ltd.', sector: 'banking' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd.', sector: 'banking' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'HEG', name: 'H.E.G. Ltd.', sector: 'it' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.', sector: 'auto' },
  { symbol: 'HEXT', name: 'Hexaware Technologies Ltd.', sector: 'it' },
  { symbol: 'HFCL', name: 'HFCL Ltd.', sector: 'it' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd.', sector: 'metals' },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper Ltd.', sector: 'metals' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.', sector: 'energy' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.', sector: 'fmcg' },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc Ltd.', sector: 'metals' },
  { symbol: 'HOMEFIRST', name: 'Home First Finance Company India Ltd.', sector: 'banking' },
  { symbol: 'HONASA', name: 'Honasa Consumer Ltd.', sector: 'fmcg' },
  { symbol: 'HONAUT', name: 'Honeywell Automation India Ltd.', sector: 'it' },
  { symbol: 'HSCL', name: 'Himadri Speciality Chemical Ltd.', sector: 'energy' },
  { symbol: 'HUDCO', name: 'Housing & Urban Development Corporation Ltd.', sector: 'banking' },
  { symbol: 'HYUNDAI', name: 'Hyundai Motor India Ltd.', sector: 'auto' },
  { symbol: 'ICICIAMC', name: 'ICICI Prudential Asset Management Company Ltd.', sector: 'banking' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd.', sector: 'banking' },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'IDBI', name: 'IDBI Bank Ltd.', sector: 'banking' },
  { symbol: 'IDEA', name: 'Vodafone Idea Ltd.', sector: 'it' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.', sector: 'banking' },
  { symbol: 'IEX', name: 'Indian Energy Exchange Ltd.', sector: 'banking' },
  { symbol: 'IFCI', name: 'IFCI Ltd.', sector: 'banking' },
  { symbol: 'IGIL', name: 'International Gemological Institute Ltd.', sector: 'general' },
  { symbol: 'IGL', name: 'Indraprastha Gas Ltd.', sector: 'energy' },
  { symbol: 'IIFL', name: 'IIFL Finance Ltd.', sector: 'banking' },
  { symbol: 'IKS', name: 'Inventurus Knowledge Solutions Ltd.', sector: 'it' },
  { symbol: 'INDGN', name: 'Indegene Ltd.', sector: 'pharma' },
  { symbol: 'INDHOTEL', name: 'Indian Hotels Co. Ltd.', sector: 'general' },
  { symbol: 'INDIACEM', name: 'India Cements Ltd.', sector: 'realestate' },
  { symbol: 'INDIAMART', name: 'Indiamart Intermesh Ltd.', sector: 'general' },
  { symbol: 'INDIANB', name: 'Indian Bank', sector: 'banking' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd.', sector: 'general' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd.', sector: 'banking' },
  { symbol: 'INDUSTOWER', name: 'Indus Towers Ltd.', sector: 'it' },
  { symbol: 'INFY', name: 'Infosys Ltd.', sector: 'it' },
  { symbol: 'INOXWIND', name: 'Inox Wind Ltd.', sector: 'it' },
  { symbol: 'INTELLECT', name: 'Intellect Design Arena Ltd.', sector: 'it' },
  { symbol: 'IOB', name: 'Indian Overseas Bank', sector: 'banking' },
  { symbol: 'IOC', name: 'Indian Oil Corporation Ltd.', sector: 'energy' },
  { symbol: 'IPCALAB', name: 'Ipca Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'IRB', name: 'IRB Infrastructure Developers Ltd.', sector: 'realestate' },
  { symbol: 'IRCON', name: 'IRCON International Ltd.', sector: 'realestate' },
  { symbol: 'IRCTC', name: 'Indian Railway Catering And Tourism Corporation Ltd.', sector: 'general' },
  { symbol: 'IREDA', name: 'Indian Renewable Energy Development Agency Ltd.', sector: 'banking' },
  { symbol: 'IRFC', name: 'Indian Railway Finance Corporation Ltd.', sector: 'banking' },
  { symbol: 'ITC', name: 'ITC Ltd.', sector: 'fmcg' },
  { symbol: 'ITCHOTELS', name: 'ITC Hotels Ltd.', sector: 'general' },
  { symbol: 'ITI', name: 'ITI Ltd.', sector: 'it' },
  { symbol: 'J&KBANK', name: 'Jammu & Kashmir Bank Ltd.', sector: 'banking' },
  { symbol: 'JAINREC', name: 'Jain Resource Recycling Ltd.', sector: 'metals' },
  { symbol: 'JBCHEPHARM', name: 'J.B. Chemicals & Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'JBMA', name: 'JBM Auto Ltd.', sector: 'auto' },
  { symbol: 'JINDALSAW', name: 'Jindal Saw Ltd.', sector: 'it' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel Ltd.', sector: 'metals' },
  { symbol: 'JIOFIN', name: 'Jio Financial Services Ltd.', sector: 'banking' },
  { symbol: 'JKCEMENT', name: 'J.K. Cement Ltd.', sector: 'realestate' },
  { symbol: 'JKTYRE', name: 'JK Tyre & Industries Ltd.', sector: 'auto' },
  { symbol: 'JMFINANCIL', name: 'JM Financial Ltd.', sector: 'banking' },
  { symbol: 'JPPOWER', name: 'Jaiprakash Power Ventures Ltd.', sector: 'power' },
  { symbol: 'JSL', name: 'Jindal Stainless Ltd.', sector: 'metals' },
  { symbol: 'JSWCEMENT', name: 'JSW Cement Ltd.', sector: 'realestate' },
  { symbol: 'JSWDULUX', name: 'JSW Dulux Ltd.', sector: 'fmcg' },
  { symbol: 'JSWENERGY', name: 'JSW Energy Ltd.', sector: 'power' },
  { symbol: 'JSWINFRA', name: 'JSW Infrastructure Ltd.', sector: 'general' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd.', sector: 'metals' },
  { symbol: 'JUBLFOOD', name: 'Jubilant Foodworks Ltd.', sector: 'general' },
  { symbol: 'JUBLINGREA', name: 'Jubilant Ingrevia Ltd.', sector: 'energy' },
  { symbol: 'JUBLPHARMA', name: 'Jubilant Pharmova Ltd.', sector: 'pharma' },
  { symbol: 'JWL', name: 'Jupiter Wagons Ltd.', sector: 'it' },
  { symbol: 'JYOTICNC', name: 'Jyoti CNC Automation Ltd.', sector: 'it' },
  { symbol: 'KAJARIACER', name: 'Kajaria Ceramics Ltd.', sector: 'fmcg' },
  { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers India Ltd.', sector: 'fmcg' },
  { symbol: 'KARURVYSYA', name: 'Karur Vysya Bank Ltd.', sector: 'banking' },
  { symbol: 'KAYNES', name: 'Kaynes Technology India Ltd.', sector: 'it' },
  { symbol: 'KEC', name: 'Kec International Ltd.', sector: 'realestate' },
  { symbol: 'KEI', name: 'KEI Industries Ltd.', sector: 'it' },
  { symbol: 'KFINTECH', name: 'Kfin Technologies Ltd.', sector: 'banking' },
  { symbol: 'KIMS', name: 'Krishna Institute of Medical Sciences Ltd.', sector: 'pharma' },
  { symbol: 'KIRLOSENG', name: 'Kirloskar Oil Eng Ltd.', sector: 'it' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', sector: 'banking' },
  { symbol: 'KPIL', name: 'Kalpataru Projects International Ltd.', sector: 'realestate' },
  { symbol: 'KPITTECH', name: 'KPIT Technologies Ltd.', sector: 'ev' },
  { symbol: 'KPRMILL', name: 'K.P.R. Mill Ltd.', sector: 'fmcg' },
  { symbol: 'LALPATHLAB', name: 'Dr. Lal Path Labs Ltd.', sector: 'pharma' },
  { symbol: 'LATENTVIEW', name: 'Latent View Analytics Ltd.', sector: 'it' },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs Ltd.', sector: 'pharma' },
  { symbol: 'LEMONTREE', name: 'Lemon Tree Hotels Ltd.', sector: 'general' },
  { symbol: 'LENSKART', name: 'Lenskart Solutions Ltd.', sector: 'general' },
  { symbol: 'LGEINDIA', name: 'LG Electronics India Ltd.', sector: 'fmcg' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance Ltd.', sector: 'banking' },
  { symbol: 'LICI', name: 'Life Insurance Corporation of India', sector: 'banking' },
  { symbol: 'LINDEINDIA', name: 'Linde India Ltd.', sector: 'energy' },
  { symbol: 'LLOYDSME', name: 'Lloyds Metals And Energy Ltd.', sector: 'metals' },
  { symbol: 'LODHA', name: 'Lodha Developers Ltd.', sector: 'realestate' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd.', sector: 'realestate' },
  { symbol: 'LTF', name: 'L&T Finance Ltd.', sector: 'banking' },
  { symbol: 'LTFOODS', name: 'LT Foods Ltd.', sector: 'fmcg' },
  { symbol: 'LTM', name: 'LTM Ltd.', sector: 'it' },
  { symbol: 'LTTS', name: 'L&T Technology Services Ltd.', sector: 'it' },
  { symbol: 'LUPIN', name: 'Lupin Ltd.', sector: 'pharma' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd.', sector: 'auto' },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services Ltd.', sector: 'banking' },
  { symbol: 'MAHABANK', name: 'Bank of Maharashtra', sector: 'banking' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd.', sector: 'gold' },
  { symbol: 'MANKIND', name: 'Mankind Pharma Ltd.', sector: 'pharma' },
  { symbol: 'MAPMYINDIA', name: 'C.E. Info Systems Ltd.', sector: 'it' },
  { symbol: 'MARICO', name: 'Marico Ltd.', sector: 'fmcg' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd.', sector: 'auto' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd.', sector: 'pharma' },
  { symbol: 'MAZDOCK', name: 'Mazagoan Dock Shipbuilders Ltd.', sector: 'it' },
  { symbol: 'MCX', name: 'Multi Commodity Exchange of India Ltd.', sector: 'banking' },
  { symbol: 'MEDANTA', name: 'Global Health Ltd.', sector: 'pharma' },
  { symbol: 'MEESHO', name: 'Meesho Ltd.', sector: 'general' },
  { symbol: 'MFSL', name: 'Max Financial Services Ltd.', sector: 'banking' },
  { symbol: 'MGL', name: 'Mahanagar Gas Ltd.', sector: 'energy' },
  { symbol: 'MINDACORP', name: 'Minda Corporation Ltd.', sector: 'auto' },
  { symbol: 'MMTC', name: 'MMTC Ltd.', sector: 'general' },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson International Ltd.', sector: 'auto' },
  { symbol: 'MOTILALOFS', name: 'Motilal Oswal Financial Services Ltd.', sector: 'banking' },
  { symbol: 'MPHASIS', name: 'MphasiS Ltd.', sector: 'it' },
  { symbol: 'MRF', name: 'MRF Ltd.', sector: 'auto' },
  { symbol: 'MRPL', name: 'Mangalore Refinery & Petrochemicals Ltd.', sector: 'energy' },
  { symbol: 'MSUMI', name: 'Motherson Sumi Wiring India Ltd.', sector: 'auto' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.', sector: 'gold' },
  { symbol: 'NAM-INDIA', name: 'Nippon Life India Asset Management Ltd.', sector: 'banking' },
  { symbol: 'NATCOPHARM', name: 'NATCO Pharma Ltd.', sector: 'pharma' },
  { symbol: 'NATIONALUM', name: 'National Aluminium Co. Ltd.', sector: 'metals' },
  { symbol: 'NAUKRI', name: 'Info Edge (India) Ltd.', sector: 'general' },
  { symbol: 'NAVA', name: 'Nava Ltd.', sector: 'power' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International Ltd.', sector: 'energy' },
  { symbol: 'NBCC', name: 'NBCC (India) Ltd.', sector: 'realestate' },
  { symbol: 'NCC', name: 'NCC Ltd.', sector: 'realestate' },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd.', sector: 'fmcg' },
  { symbol: 'NETWEB', name: 'Netweb Technologies India Ltd.', sector: 'it' },
  { symbol: 'NEULANDLAB', name: 'Neuland Laboratories Ltd.', sector: 'pharma' },
  { symbol: 'NEWGEN', name: 'Newgen Software Technologies Ltd.', sector: 'it' },
  { symbol: 'NH', name: 'Narayana Hrudayalaya Ltd.', sector: 'pharma' },
  { symbol: 'NHPC', name: 'NHPC Ltd.', sector: 'power' },
  { symbol: 'NIACL', name: 'The New India Assurance Company Ltd.', sector: 'banking' },
  { symbol: 'NIVABUPA', name: 'Niva Bupa Health Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'NLCINDIA', name: 'NLC India Ltd.', sector: 'power' },
  { symbol: 'NMDC', name: 'NMDC Ltd.', sector: 'metals' },
  { symbol: 'NSLNISP', name: 'NMDC Steel Ltd.', sector: 'metals' },
  { symbol: 'NTPC', name: 'NTPC Ltd.', sector: 'power' },
  { symbol: 'NTPCGREEN', name: 'NTPC Green Energy Ltd.', sector: 'power' },
  { symbol: 'NUVAMA', name: 'Nuvama Wealth Management Ltd.', sector: 'banking' },
  { symbol: 'NUVOCO', name: 'Nuvoco Vistas Corporation Ltd.', sector: 'realestate' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd.', sector: 'general' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd.', sector: 'realestate' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software Ltd.', sector: 'it' },
  { symbol: 'OIL', name: 'Oil India Ltd.', sector: 'energy' },
  { symbol: 'OLAELEC', name: 'Ola Electric Mobility Ltd.', sector: 'auto' },
  { symbol: 'OLECTRA', name: 'Olectra Greentech Ltd.', sector: 'ev' },
  { symbol: 'ONESOURCE', name: 'Onesource Specialty Pharma Ltd.', sector: 'pharma' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.', sector: 'energy' },
  { symbol: 'PAGEIND', name: 'Page Industries Ltd.', sector: 'fmcg' },
  { symbol: 'PARADEEP', name: 'Paradeep Phosphates Ltd.', sector: 'energy' },
  { symbol: 'PATANJALI', name: 'Patanjali Foods Ltd.', sector: 'fmcg' },
  { symbol: 'PAYTM', name: 'One 97 Communications Ltd.', sector: 'banking' },
  { symbol: 'PCBL', name: 'PCBL Chemical Ltd.', sector: 'energy' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems Ltd.', sector: 'it' },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd.', sector: 'energy' },
  { symbol: 'PFC', name: 'Power Finance Corporation Ltd.', sector: 'banking' },
  { symbol: 'PFIZER', name: 'Pfizer Ltd.', sector: 'pharma' },
  { symbol: 'PGEL', name: 'PG Electroplast Ltd.', sector: 'fmcg' },
  { symbol: 'PHOENIXLTD', name: 'Phoenix Mills Ltd.', sector: 'realestate' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries Ltd.', sector: 'energy' },
  { symbol: 'PIIND', name: 'PI Industries Ltd.', sector: 'energy' },
  { symbol: 'PINELABS', name: 'Pine Labs Ltd.', sector: 'banking' },
  { symbol: 'PIRAMALFIN', name: 'Piramal Finance Ltd.', sector: 'banking' },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'banking' },
  { symbol: 'PNBHOUSING', name: 'PNB Housing Finance Ltd.', sector: 'banking' },
  { symbol: 'POLICYBZR', name: 'PB Fintech Ltd.', sector: 'banking' },
  { symbol: 'POLYCAB', name: 'Polycab India Ltd.', sector: 'it' },
  { symbol: 'POLYMED', name: 'Poly Medicure Ltd.', sector: 'pharma' },
  { symbol: 'POONAWALLA', name: 'Poonawalla Fincorp Ltd.', sector: 'banking' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.', sector: 'power' },
  { symbol: 'POWERINDIA', name: 'Hitachi Energy India Ltd.', sector: 'it' },
  { symbol: 'PPLPHARMA', name: 'Piramal Pharma Ltd.', sector: 'pharma' },
  { symbol: 'PREMIERENE', name: 'Premier Energies Ltd.', sector: 'it' },
  { symbol: 'PRESTIGE', name: 'Prestige Estates Projects Ltd.', sector: 'realestate' },
  { symbol: 'PTCIL', name: 'PTC Industries Ltd.', sector: 'it' },
  { symbol: 'PVRINOX', name: 'PVR INOX Ltd.', sector: 'general' },
  { symbol: 'PWL', name: 'Physicswallah Ltd.', sector: 'general' },
  { symbol: 'RADICO', name: 'Radico Khaitan Ltd', sector: 'fmcg' },
  { symbol: 'RAILTEL', name: 'Railtel Corporation Of India Ltd.', sector: 'it' },
  { symbol: 'RAINBOW', name: 'Rainbow Childrens Medicare Ltd.', sector: 'pharma' },
  { symbol: 'RAMCOCEM', name: 'The Ramco Cements Ltd.', sector: 'realestate' },
  { symbol: 'RBLBANK', name: 'RBL Bank Ltd.', sector: 'banking' },
  { symbol: 'RECLTD', name: 'REC Ltd.', sector: 'banking' },
  { symbol: 'REDINGTON', name: 'Redington Ltd.', sector: 'general' },
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd.', sector: 'energy' },
  { symbol: 'RHIM', name: 'RHI MAGNESITA INDIA LTD.', sector: 'it' },
  { symbol: 'RITES', name: 'RITES Ltd.', sector: 'realestate' },
  { symbol: 'RKFORGE', name: 'Ramkrishna Forgings Ltd.', sector: 'auto' },
  { symbol: 'RPOWER', name: 'Reliance Power Ltd.', sector: 'power' },
  { symbol: 'RRKABEL', name: 'R R Kabel Ltd.', sector: 'it' },
  { symbol: 'RVNL', name: 'Rail Vikas Nigam Ltd.', sector: 'realestate' },
  { symbol: 'SAGILITY', name: 'Sagility Ltd.', sector: 'it' },
  { symbol: 'SAIL', name: 'Steel Authority of India Ltd.', sector: 'metals' },
  { symbol: 'SAILIFE', name: 'Sai Life Sciences Ltd.', sector: 'pharma' },
  { symbol: 'SAMMAANCAP', name: 'Sammaan Capital Ltd.', sector: 'banking' },
  { symbol: 'SAPPHIRE', name: 'Sapphire Foods India Ltd.', sector: 'general' },
  { symbol: 'SARDAEN', name: 'Sarda Energy and Minerals Ltd.', sector: 'metals' },
  { symbol: 'SAREGAMA', name: 'Saregama India Ltd', sector: 'general' },
  { symbol: 'SBFC', name: 'SBFC Finance Ltd.', sector: 'banking' },
  { symbol: 'SBICARD', name: 'SBI Cards and Payment Services Ltd.', sector: 'banking' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'banking' },
  { symbol: 'SCHAEFFLER', name: 'Schaeffler India Ltd.', sector: 'auto' },
  { symbol: 'SCHNEIDER', name: 'Schneider Electric Infrastructure Ltd.', sector: 'it' },
  { symbol: 'SCI', name: 'Shipping Corporation of India Ltd.', sector: 'general' },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd.', sector: 'realestate' },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance Ltd.', sector: 'banking' },
  { symbol: 'SHYAMMETL', name: 'Shyam Metalics and Energy Ltd.', sector: 'it' },
  { symbol: 'SIEMENS', name: 'Siemens Ltd.', sector: 'it' },
  { symbol: 'SIGNATURE', name: 'Signatureglobal (India) Ltd.', sector: 'realestate' },
  { symbol: 'SJVN', name: 'SJVN Ltd.', sector: 'power' },
  { symbol: 'SOBHA', name: 'Sobha Ltd.', sector: 'realestate' },
  { symbol: 'SOLARINDS', name: 'Solar Industries India Ltd.', sector: 'defense' },
  { symbol: 'SONACOMS', name: 'Sona BLW Precision Forgings Ltd.', sector: 'auto' },
  { symbol: 'SONATSOFTW', name: 'Sonata Software Ltd.', sector: 'it' },
  { symbol: 'SPLPETRO', name: 'Supreme Petrochem Ltd.', sector: 'energy' },
  { symbol: 'SRF', name: 'SRF Ltd.', sector: 'energy' },
  { symbol: 'STARHEALTH', name: 'Star Health and Allied Insurance Company Ltd.', sector: 'banking' },
  { symbol: 'SUMICHEM', name: 'Sumitomo Chemical India Ltd.', sector: 'energy' },
  { symbol: 'SUNDARMFIN', name: 'Sundaram Finance Ltd.', sector: 'banking' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.', sector: 'pharma' },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd.', sector: 'general' },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries Ltd.', sector: 'it' },
  { symbol: 'SUZLON', name: 'Suzlon Energy Ltd.', sector: 'it' },
  { symbol: 'SWANCORP', name: 'Swan Corp Ltd.', sector: 'energy' },
  { symbol: 'SWIGGY', name: 'Swiggy Ltd.', sector: 'general' },
  { symbol: 'SYNGENE', name: 'Syngene International Ltd.', sector: 'pharma' },
  { symbol: 'SYRMA', name: 'Syrma SGS Technology Ltd.', sector: 'it' },
  { symbol: 'TARIL', name: 'Transformers And Rectifiers (India) Ltd.', sector: 'it' },
  { symbol: 'TATACAP', name: 'Tata Capital Ltd.', sector: 'banking' },
  { symbol: 'TATACHEM', name: 'Tata Chemicals Ltd.', sector: 'energy' },
  { symbol: 'TATACOMM', name: 'Tata Communications Ltd.', sector: 'it' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd.', sector: 'fmcg' },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi Ltd.', sector: 'ev' },
  { symbol: 'TATAINVEST', name: 'Tata Investment Corporation Ltd.', sector: 'banking' },
  { symbol: 'TATAPOWER', name: 'Tata Power Co. Ltd.', sector: 'power' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd.', sector: 'metals' },
  { symbol: 'TATATECH', name: 'Tata Technologies Ltd.', sector: 'it' },
  { symbol: 'TBOTEK', name: 'TBO Tek Ltd.', sector: 'general' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd.', sector: 'it' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd.', sector: 'it' },
  { symbol: 'TECHNOE', name: 'Techno Electric & Engineering Company Ltd.', sector: 'realestate' },
  { symbol: 'TEGA', name: 'Tega Industries Ltd.', sector: 'it' },
  { symbol: 'TEJASNET', name: 'Tejas Networks Ltd.', sector: 'it' },
  { symbol: 'TENNIND', name: 'Tenneco Clean Air India Ltd.', sector: 'auto' },
  { symbol: 'THELEELA', name: 'Leela Palaces Hotels & Resorts Ltd.', sector: 'general' },
  { symbol: 'THERMAX', name: 'Thermax Ltd.', sector: 'it' },
  { symbol: 'TIINDIA', name: 'Tube Investments of India Ltd.', sector: 'auto' },
  { symbol: 'TIMKEN', name: 'Timken India Ltd.', sector: 'it' },
  { symbol: 'TITAGARH', name: 'Titagarh Rail Systems Ltd.', sector: 'it' },
  { symbol: 'TITAN', name: 'Titan Company Ltd.', sector: 'gold' },
  { symbol: 'TMCV', name: 'Tata Motors Ltd.', sector: 'ev' },
  { symbol: 'TMPV', name: 'Tata Motors Passenger Vehicles Ltd.', sector: 'auto' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', sector: 'pharma' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power Ltd.', sector: 'power' },
  { symbol: 'TRAVELFOOD', name: 'Travel Food Services Ltd.', sector: 'general' },
  { symbol: 'TRENT', name: 'Trent Ltd.', sector: 'general' },
  { symbol: 'TRIDENT', name: 'Trident Ltd.', sector: 'fmcg' },
  { symbol: 'TRITURBINE', name: 'Triveni Turbine Ltd.', sector: 'it' },
  { symbol: 'TTML', name: 'Tata Teleservices (Maharashtra) Ltd.', sector: 'it' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company Ltd.', sector: 'auto' },
  { symbol: 'UBL', name: 'United Breweries Ltd.', sector: 'fmcg' },
  { symbol: 'UCOBANK', name: 'UCO Bank', sector: 'banking' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.', sector: 'realestate' },
  { symbol: 'UNIONBANK', name: 'Union Bank of India', sector: 'banking' },
  { symbol: 'UNITDSPR', name: 'United Spirits Ltd.', sector: 'fmcg' },
  { symbol: 'UNOMINDA', name: 'UNO Minda Ltd.', sector: 'auto' },
  { symbol: 'UPL', name: 'UPL Ltd.', sector: 'energy' },
  { symbol: 'URBANCO', name: 'Urban Company Ltd.', sector: 'general' },
  { symbol: 'USHAMART', name: 'Usha Martin Ltd.', sector: 'it' },
  { symbol: 'UTIAMC', name: 'UTI Asset Management Company Ltd.', sector: 'banking' },
  { symbol: 'VAML', name: 'Vedanta Aluminium Metal Ltd.', sector: 'metals' },
  { symbol: 'VBL', name: 'Varun Beverages Ltd.', sector: 'fmcg' },
  { symbol: 'VEDL', name: 'Vedanta Ltd.', sector: 'metals' },
  { symbol: 'VIJAYA', name: 'Vijaya Diagnostic Centre Ltd.', sector: 'pharma' },
  { symbol: 'VMM', name: 'Vishal Mega Mart Ltd.', sector: 'general' },
  { symbol: 'VOGL', name: 'Vedanta Oil and Gas Ltd.', sector: 'energy' },
  { symbol: 'VOLTAS', name: 'Voltas Ltd.', sector: 'fmcg' },
  { symbol: 'VTL', name: 'Vardhman Textiles Ltd.', sector: 'fmcg' },
  { symbol: 'WAAREEENER', name: 'Waaree Energies Ltd.', sector: 'it' },
  { symbol: 'WELCORP', name: 'Welspun Corp Ltd.', sector: 'it' },
  { symbol: 'WELSPUNLIV', name: 'Welspun Living Ltd.', sector: 'fmcg' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool of India Ltd.', sector: 'fmcg' },
  { symbol: 'WIPRO', name: 'Wipro Ltd.', sector: 'it' },
  { symbol: 'WOCKPHARMA', name: 'Wockhardt Ltd.', sector: 'pharma' },
  { symbol: 'YESBANK', name: 'Yes Bank Ltd.', sector: 'banking' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.', sector: 'general' },
  { symbol: 'ZENSARTECH', name: 'Zensar Technolgies Ltd.', sector: 'it' },
  { symbol: 'ZENTEC', name: 'Zen Technologies Ltd.', sector: 'it' },
  { symbol: 'ZFCVINDIA', name: 'ZF Commercial Vehicle Control Systems India Ltd.', sector: 'auto' },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd.', sector: 'pharma' },
  { symbol: 'ZYDUSWELL', name: 'Zydus Wellness Ltd.', sector: 'fmcg' },
];

// Global regions and their impact on Indian sectors
export const GLOBAL_IMPACT_MAP: Record<string, { region: string; sectors: string[]; description: string }[]> = {
  'Middle East': [
    { region: 'Middle East', sectors: ['energy', 'gold', 'defense'], description: 'Oil supply disruption, safe-haven demand for gold, defense spending' },
  ],
  'USA': [
    { region: 'USA', sectors: ['it', 'pharma', 'banking'], description: 'Tech spending, FDA approvals, Fed rate impact on FII flows' },
  ],
  'China': [
    { region: 'China', sectors: ['metals', 'auto', 'ev'], description: 'Steel/commodity demand, EV battery supply, trade dynamics' },
  ],
  'Europe': [
    { region: 'Europe', sectors: ['auto', 'pharma', 'it'], description: 'Auto exports, pharma regulations, IT services demand' },
  ],
  'Russia-Ukraine': [
    { region: 'Russia-Ukraine', sectors: ['energy', 'metals', 'defense', 'gold'], description: 'Energy prices, commodity supply, geopolitical risk premium' },
  ],
};

export function getStockBySymbol(symbol: string) {
  return ALL_STOCKS.find(s => s.symbol.toLowerCase() === symbol.toLowerCase());
}

export function getStocksBySector(sectorId: string) {
  return ALL_STOCKS.filter(s => s.sector === sectorId);
}

export function searchStocks(query: string) {
  const q = query.toLowerCase();
  return ALL_STOCKS.filter(
    s => s.symbol.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)
  ).slice(0, 10);
}
